name: Build ImmortalWrt (External Config)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 🚀 缓存
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          immortalwrt/dl
          immortalwrt/staging_dir
          immortalwrt/build_dir
        key: immortalwrt-${{ runner.os }}-${{ hashFiles('config/.config') }}
        restore-keys: |
          immortalwrt-${{ runner.os }}

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone Source
      run: |
        git clone -b openwrt-23.05 https://github.com/immortalwrt/immortalwrt.git
        cd immortalwrt

        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages" >> feeds.conf.default
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
        echo "src-git openclash https://github.com/vernesong/OpenClash" >> feeds.conf.default

        ./scripts/feeds update -a
        ./scripts/feeds install -a

    # ⭐ 核心：复制 config
    - name: Load Config
      run: |
        cp config/.config immortalwrt/.config

    - name: Add OpenClash Core
      run: |
        CORE_DIR="immortalwrt/package/luci-app-openclash/root/etc/openclash/core"
        mkdir -p $CORE_DIR
        wget -qO $CORE_DIR/clash_meta https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64
        chmod +x $CORE_DIR/clash_meta

    - name: Defconfig
      run: |
        cd immortalwrt
        make defconfig

    - name: Download
      run: |
        cd immortalwrt
        make download -j$(nproc)

    - name: Build
      run: |
        cd immortalwrt
        make -j$(nproc) || make -j1 V=s

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-x86-64
        path: immortalwrt/bin/targets/x86/64/
